### PR TITLE
New Footer and PropTypes refactoring

### PR DESCRIPTION
**Pull request by DusanSacha**

### CODE REVIEW

**Comment by DusanSacha** [comment]
Hi @ovidiubute,
could you please check?
For start, I did some refactoring (PropTypes) and re-implemented Footer component.

Thanks!

**Comment by ovidiubute** [comment]
Looks like CircleCI configuration has changed since we last rebuilt this :)

**Comment by ovidiubute** [comment]
@DusanSacha I'm trying to fix CircleCI in this PR, I'll be working only in the `circle.yml` file.

**Comment by ovidiubute** [comment]
It's now live :) I had to also fix the Netlify integration because it wasn't working anymore.

**Pull request merged**
